imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_addresses: ['me@example.com']

# React  Configuration
limenius_react:
    # Other options are "server_side" and "client_side"
    default_rendering: "client_side"
    serverside_rendering:
        # In case of error in server-side rendering, throw exception
        fail_loud: false
        # Replay every console.log message produced during server-side rendering
        # in the JavaScript console
        # Note that if enabled it will throw a (harmless) React warning
        trace: false
        # Mode can be `"phpexecjs"` (to execute Js from PHP using PhpExecJs),
        # or `"external_server"` (to rely on an external node.js server)
        # Default is `"phpexecjs"`
        mode: "phpexecjs"
        # Location of the server bundle, that contains React and React on Rails.
        # null will default to `%kernel.root_dir%/Resources/webpack/server-bundle.js`
        # Only used with mode `phpexecjs`
        server_bundle_path: null
        # Only used with mode `external`
        # Location of the unix socket to communicate with a dummy node.js server
        # Such as the one in `Resources/node-server/server.js`
        # null will default to `%kernel.root_dir%/Resources/node-server/node.sock
        server_socket_path: null